%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'bgg4_model0';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('bgg4_model0.log');
M_.exo_names = 'e_a';
M_.exo_names_tex = 'e\_a';
M_.exo_names_long = 'e_a';
M_.exo_names = char(M_.exo_names, 'e_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g');
M_.exo_names_long = char(M_.exo_names_long, 'e_g');
M_.exo_names = char(M_.exo_names, 'e_z');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_z');
M_.exo_names_long = char(M_.exo_names_long, 'e_z');
M_.exo_names = char(M_.exo_names, 'e_rnomstar');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_rnomstar');
M_.exo_names_long = char(M_.exo_names_long, 'e_rnomstar');
M_.exo_names = char(M_.exo_names, 'e_pistar');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_pistar');
M_.exo_names_long = char(M_.exo_names_long, 'e_pistar');
M_.exo_names = char(M_.exo_names, 'e_prcostar');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_prcostar');
M_.exo_names_long = char(M_.exo_names_long, 'e_prcostar');
M_.exo_names = char(M_.exo_names, 'e_yco');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_yco');
M_.exo_names_long = char(M_.exo_names_long, 'e_yco');
M_.exo_names = char(M_.exo_names, 'e_ystar');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ystar');
M_.exo_names_long = char(M_.exo_names_long, 'e_ystar');
M_.endo_names = 'c';
M_.endo_names_tex = 'c';
M_.endo_names_long = 'c';
M_.endo_names = char(M_.endo_names, 'rnom');
M_.endo_names_tex = char(M_.endo_names_tex, 'rnom');
M_.endo_names_long = char(M_.endo_names_long, 'rnom');
M_.endo_names = char(M_.endo_names, 'pic');
M_.endo_names_tex = char(M_.endo_names_tex, 'pic');
M_.endo_names_long = char(M_.endo_names_long, 'pic');
M_.endo_names = char(M_.endo_names, 'lab');
M_.endo_names_tex = char(M_.endo_names_tex, 'lab');
M_.endo_names_long = char(M_.endo_names_long, 'lab');
M_.endo_names = char(M_.endo_names, 'wr');
M_.endo_names_tex = char(M_.endo_names_tex, 'wr');
M_.endo_names_long = char(M_.endo_names_long, 'wr');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'mcr');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcr');
M_.endo_names_long = char(M_.endo_names_long, 'mcr');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv');
M_.endo_names_long = char(M_.endo_names_long, 'inv');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'ce');
M_.endo_names_tex = char(M_.endo_names_tex, 'ce');
M_.endo_names_long = char(M_.endo_names_long, 'ce');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'qr');
M_.endo_names_tex = char(M_.endo_names_tex, 'qr');
M_.endo_names_long = char(M_.endo_names_long, 'qr');
M_.endo_names = char(M_.endo_names, 'sp');
M_.endo_names_tex = char(M_.endo_names_tex, 'sp');
M_.endo_names_long = char(M_.endo_names_long, 'sp');
M_.endo_names = char(M_.endo_names, 'mrs');
M_.endo_names_tex = char(M_.endo_names_tex, 'mrs');
M_.endo_names_long = char(M_.endo_names_long, 'mrs');
M_.endo_names = char(M_.endo_names, 'piw');
M_.endo_names_tex = char(M_.endo_names_tex, 'piw');
M_.endo_names_long = char(M_.endo_names_long, 'piw');
M_.endo_names = char(M_.endo_names, 'yh');
M_.endo_names_tex = char(M_.endo_names_tex, 'yh');
M_.endo_names_long = char(M_.endo_names_long, 'yh');
M_.endo_names = char(M_.endo_names, 'dh');
M_.endo_names_tex = char(M_.endo_names_tex, 'dh');
M_.endo_names_long = char(M_.endo_names_long, 'dh');
M_.endo_names = char(M_.endo_names, 'chstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'chstar');
M_.endo_names_long = char(M_.endo_names_long, 'chstar');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'prh');
M_.endo_names_tex = char(M_.endo_names_tex, 'prh');
M_.endo_names_long = char(M_.endo_names_long, 'prh');
M_.endo_names = char(M_.endo_names, 'pri');
M_.endo_names_tex = char(M_.endo_names_tex, 'pri');
M_.endo_names_long = char(M_.endo_names_long, 'pri');
M_.endo_names = char(M_.endo_names, 'prx');
M_.endo_names_tex = char(M_.endo_names_tex, 'prx');
M_.endo_names_long = char(M_.endo_names_long, 'prx');
M_.endo_names = char(M_.endo_names, 'rer');
M_.endo_names_tex = char(M_.endo_names_tex, 'rer');
M_.endo_names_long = char(M_.endo_names_long, 'rer');
M_.endo_names = char(M_.endo_names, 'dep');
M_.endo_names_tex = char(M_.endo_names_tex, 'dep');
M_.endo_names_long = char(M_.endo_names_long, 'dep');
M_.endo_names = char(M_.endo_names, 'bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'bf');
M_.endo_names_long = char(M_.endo_names_long, 'bf');
M_.endo_names = char(M_.endo_names, 'prf');
M_.endo_names_tex = char(M_.endo_names_tex, 'prf');
M_.endo_names_long = char(M_.endo_names_long, 'prf');
M_.endo_names = char(M_.endo_names, 'pif');
M_.endo_names_tex = char(M_.endo_names_tex, 'pif');
M_.endo_names_long = char(M_.endo_names_long, 'pif');
M_.endo_names = char(M_.endo_names, 'pih');
M_.endo_names_tex = char(M_.endo_names_tex, 'pih');
M_.endo_names_long = char(M_.endo_names_long, 'pih');
M_.endo_names = char(M_.endo_names, 'rnomstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'rnomstar');
M_.endo_names_long = char(M_.endo_names_long, 'rnomstar');
M_.endo_names = char(M_.endo_names, 'pistar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pistar');
M_.endo_names_long = char(M_.endo_names_long, 'pistar');
M_.endo_names = char(M_.endo_names, 'prcostar');
M_.endo_names_tex = char(M_.endo_names_tex, 'prcostar');
M_.endo_names_long = char(M_.endo_names_long, 'prcostar');
M_.endo_names = char(M_.endo_names, 'yco');
M_.endo_names_tex = char(M_.endo_names_tex, 'yco');
M_.endo_names_long = char(M_.endo_names_long, 'yco');
M_.endo_names = char(M_.endo_names, 'ystar');
M_.endo_names_tex = char(M_.endo_names_tex, 'ystar');
M_.endo_names_long = char(M_.endo_names_long, 'ystar');
M_.endo_partitions = struct();
M_.param_names = 'FINACC';
M_.param_names_tex = 'FINACC';
M_.param_names_long = 'FINACC';
M_.param_names = char(M_.param_names, 'beta_C');
M_.param_names_tex = char(M_.param_names_tex, 'beta\_C');
M_.param_names_long = char(M_.param_names_long, 'beta_C');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'sigma_L');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_L');
M_.param_names_long = char(M_.param_names_long, 'sigma_L');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'G_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_Y');
M_.param_names = char(M_.param_names, 'chi_inv');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_inv');
M_.param_names_long = char(M_.param_names_long, 'chi_inv');
M_.param_names = char(M_.param_names, 'RK');
M_.param_names_tex = char(M_.param_names_tex, 'RK');
M_.param_names_long = char(M_.param_names_long, 'RK');
M_.param_names = char(M_.param_names, 'YH_K');
M_.param_names_tex = char(M_.param_names_tex, 'YH\_K');
M_.param_names_long = char(M_.param_names_long, 'YH_K');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'I_Y');
M_.param_names_tex = char(M_.param_names_tex, 'I\_Y');
M_.param_names_long = char(M_.param_names_long, 'I_Y');
M_.param_names = char(M_.param_names, 'K_N');
M_.param_names_tex = char(M_.param_names_tex, 'K\_N');
M_.param_names_long = char(M_.param_names_long, 'K_N');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'sigma_lomega');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_lomega');
M_.param_names_long = char(M_.param_names_long, 'sigma_lomega');
M_.param_names = char(M_.param_names, 'mu');
M_.param_names_tex = char(M_.param_names_tex, 'mu');
M_.param_names_long = char(M_.param_names_long, 'mu');
M_.param_names = char(M_.param_names, 'CE_Y');
M_.param_names_tex = char(M_.param_names_tex, 'CE\_Y');
M_.param_names_long = char(M_.param_names_long, 'CE_Y');
M_.param_names = char(M_.param_names, 'C_Y');
M_.param_names_tex = char(M_.param_names_tex, 'C\_Y');
M_.param_names_long = char(M_.param_names_long, 'C_Y');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'theta_w');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_w');
M_.param_names_long = char(M_.param_names_long, 'theta_w');
M_.param_names = char(M_.param_names, 'chi_w');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_w');
M_.param_names_long = char(M_.param_names_long, 'chi_w');
M_.param_names = char(M_.param_names, 'eps_L');
M_.param_names_tex = char(M_.param_names_tex, 'eps\_L');
M_.param_names_long = char(M_.param_names_long, 'eps_L');
M_.param_names = char(M_.param_names, 'theta_h');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_h');
M_.param_names_long = char(M_.param_names_long, 'theta_h');
M_.param_names = char(M_.param_names, 'chi_h');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_h');
M_.param_names_long = char(M_.param_names_long, 'chi_h');
M_.param_names = char(M_.param_names, 'theta_f');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_f');
M_.param_names_long = char(M_.param_names_long, 'theta_f');
M_.param_names = char(M_.param_names, 'chi_f');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_f');
M_.param_names_long = char(M_.param_names_long, 'chi_f');
M_.param_names = char(M_.param_names, 'rho_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_i');
M_.param_names = char(M_.param_names, 'phi_pic');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_pic');
M_.param_names_long = char(M_.param_names_long, 'phi_pic');
M_.param_names = char(M_.param_names, 'phi_y');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_y');
M_.param_names_long = char(M_.param_names_long, 'phi_y');
M_.param_names = char(M_.param_names, 'phi_dep');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_dep');
M_.param_names_long = char(M_.param_names_long, 'phi_dep');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'rho_z');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_z');
M_.param_names_long = char(M_.param_names_long, 'rho_z');
M_.param_names = char(M_.param_names, 'alpha_I');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_I');
M_.param_names_long = char(M_.param_names_long, 'alpha_I');
M_.param_names = char(M_.param_names, 'alpha_C');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_C');
M_.param_names_long = char(M_.param_names_long, 'alpha_C');
M_.param_names = char(M_.param_names, 'eta_C');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_C');
M_.param_names_long = char(M_.param_names_long, 'eta_C');
M_.param_names = char(M_.param_names, 'eta_I');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_I');
M_.param_names_long = char(M_.param_names_long, 'eta_I');
M_.param_names = char(M_.param_names, 'eta_star');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_star');
M_.param_names_long = char(M_.param_names_long, 'eta_star');
M_.param_names = char(M_.param_names, 'YCO_Y');
M_.param_names_tex = char(M_.param_names_tex, 'YCO\_Y');
M_.param_names_long = char(M_.param_names_long, 'YCO_Y');
M_.param_names = char(M_.param_names, 'NX_Y');
M_.param_names_tex = char(M_.param_names_tex, 'NX\_Y');
M_.param_names_long = char(M_.param_names_long, 'NX_Y');
M_.param_names = char(M_.param_names, 'YH_Y');
M_.param_names_tex = char(M_.param_names_tex, 'YH\_Y');
M_.param_names_long = char(M_.param_names_long, 'YH_Y');
M_.param_names = char(M_.param_names, 'M_Y');
M_.param_names_tex = char(M_.param_names_tex, 'M\_Y');
M_.param_names_long = char(M_.param_names_long, 'M_Y');
M_.param_names = char(M_.param_names, 'X_Y');
M_.param_names_tex = char(M_.param_names_tex, 'X\_Y');
M_.param_names_long = char(M_.param_names_long, 'X_Y');
M_.param_names = char(M_.param_names, 'varphi');
M_.param_names_tex = char(M_.param_names_tex, 'varphi');
M_.param_names_long = char(M_.param_names_long, 'varphi');
M_.param_names = char(M_.param_names, 'varrho');
M_.param_names_tex = char(M_.param_names_tex, 'varrho');
M_.param_names_long = char(M_.param_names_long, 'varrho');
M_.param_names = char(M_.param_names, 'BF_Y');
M_.param_names_tex = char(M_.param_names_tex, 'BF\_Y');
M_.param_names_long = char(M_.param_names_long, 'BF_Y');
M_.param_names = char(M_.param_names, 'CCE_Y');
M_.param_names_tex = char(M_.param_names_tex, 'CCE\_Y');
M_.param_names_long = char(M_.param_names_long, 'CCE_Y');
M_.param_names = char(M_.param_names, 'CHstar_Y');
M_.param_names_tex = char(M_.param_names_tex, 'CHstar\_Y');
M_.param_names_long = char(M_.param_names_long, 'CHstar_Y');
M_.param_names = char(M_.param_names, 'rho_rnomstar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_rnomstar');
M_.param_names_long = char(M_.param_names_long, 'rho_rnomstar');
M_.param_names = char(M_.param_names, 'rho_pistar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_pistar');
M_.param_names_long = char(M_.param_names_long, 'rho_pistar');
M_.param_names = char(M_.param_names, 'rho_prcostar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_prcostar');
M_.param_names_long = char(M_.param_names_long, 'rho_prcostar');
M_.param_names = char(M_.param_names, 'rho_yco');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_yco');
M_.param_names_long = char(M_.param_names_long, 'rho_yco');
M_.param_names = char(M_.param_names, 'rho_ystar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ystar');
M_.param_names_long = char(M_.param_names_long, 'rho_ystar');
M_.param_names = char(M_.param_names, 'sigma_rnomstar');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_rnomstar');
M_.param_names_long = char(M_.param_names_long, 'sigma_rnomstar');
M_.param_names = char(M_.param_names, 'sigma_pistar');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_pistar');
M_.param_names_long = char(M_.param_names_long, 'sigma_pistar');
M_.param_names = char(M_.param_names, 'sigma_prcostar');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_prcostar');
M_.param_names_long = char(M_.param_names_long, 'sigma_prcostar');
M_.param_names = char(M_.param_names, 'sigma_yco');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_yco');
M_.param_names_long = char(M_.param_names_long, 'sigma_yco');
M_.param_names = char(M_.param_names, 'sigma_ystar');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ystar');
M_.param_names_long = char(M_.param_names_long, 'sigma_ystar');
M_.param_names = char(M_.param_names, 'sigma_z');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_z');
M_.param_names_long = char(M_.param_names_long, 'sigma_z');
M_.param_names = char(M_.param_names, 'sigma_g');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_g');
M_.param_names_long = char(M_.param_names_long, 'sigma_g');
M_.param_names = char(M_.param_names, 'sigma_a');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_a');
M_.param_names_long = char(M_.param_names_long, 'sigma_a');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 38;
M_.param_nbr = 62;
M_.orig_endo_nbr = 38;
M_.aux_vars = [];
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('bgg4_model0_static');
erase_compiled_function('bgg4_model0_dynamic');
M_.orig_eq_nbr = 38;
M_.eq_nbr = 38;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 24 62;
 2 25 0;
 3 26 63;
 0 27 0;
 4 28 0;
 0 29 0;
 0 30 0;
 5 31 0;
 6 32 0;
 7 33 0;
 8 34 64;
 9 35 0;
 10 36 0;
 0 37 0;
 0 38 65;
 11 39 0;
 12 40 0;
 0 41 0;
 0 42 66;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 13 48 0;
 0 49 0;
 0 50 0;
 14 51 0;
 0 52 67;
 15 53 0;
 16 54 0;
 17 55 68;
 18 56 69;
 19 57 0;
 20 58 0;
 21 59 0;
 22 60 0;
 23 61 0;]';
M_.nstatic = 12;
M_.nfwrd   = 3;
M_.npred   = 18;
M_.nboth   = 5;
M_.nsfwrd   = 8;
M_.nspred   = 23;
M_.ndynamic   = 26;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(38, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(62, 1);
M_.NNZDerivatives = [159; -1; -1];
M_.params( 1 ) = 0;
FINACC = M_.params( 1 );
M_.params( 2 ) = 0.995;
beta_C = M_.params( 2 );
M_.params( 3 ) = 1;
sigma = M_.params( 3 );
M_.params( 4 ) = 0;
h = M_.params( 4 );
M_.params( 5 ) = 1;
sigma_L = M_.params( 5 );
M_.params( 6 ) = 0.34;
alpha = M_.params( 6 );
M_.params( 7 ) = 0.03;
delta = M_.params( 7 );
M_.params( 8 ) = 0.12;
G_Y = M_.params( 8 );
M_.params( 9 ) = 20;
chi_inv = M_.params( 9 );
M_.params( 10 ) = (0.03+(1/M_.params(2))^4)^0.25;
RK = M_.params( 10 );
DEF_RATE= 0.0075;
M_.params( 11 ) = (M_.params(10)-(1-M_.params(7)))/M_.params(6);
YH_K = M_.params( 11 );
M_.params( 12 ) = (1-M_.params(7))/M_.params(10);
epsilon = M_.params( 12 );
M_.params( 40 ) = 0.12;
YCO_Y = M_.params( 40 );
M_.params( 41 ) = 0.05;
NX_Y = M_.params( 41 );
M_.params( 45 ) = 0.5;
varphi = M_.params( 45 );
M_.params( 36 ) = 0.33;
alpha_C = M_.params( 36 );
M_.params( 35 ) = 0.50;
alpha_I = M_.params( 35 );
M_.params( 37 ) = 0.5;
eta_C = M_.params( 37 );
M_.params( 38 ) = 0.5;
eta_I = M_.params( 38 );
M_.params( 39 ) = 0.5;
eta_star = M_.params( 39 );
M_.params( 46 ) = 0.001;
varrho = M_.params( 46 );
REM_Y   = varphi*YCO_Y - (NX_Y-0.0025);
M_.params( 47 ) = 1/(1/M_.params(2)-1)*(M_.params(41)-M_.params(45)*M_.params(40)+REM_Y);
BF_Y = M_.params( 47 );
M_.params( 42 ) = 1-M_.params(40);
YH_Y = M_.params( 42 );
M_.params( 13 ) = M_.params(7)/M_.params(11)*M_.params(42);
I_Y = M_.params( 13 );
M_.params( 48 ) = 1-M_.params(13)-M_.params(41)-M_.params(8);
CCE_Y = M_.params( 48 );
M_.params( 43 ) = M_.params(36)*M_.params(48)+M_.params(13)*M_.params(35);
M_Y = M_.params( 43 );
M_.params( 44 ) = M_.params(41)+M_.params(43);
X_Y = M_.params( 44 );
M_.params( 49 ) = M_.params(44)-M_.params(40);
CHstar_Y = M_.params( 49 );
M_.params( 14 ) = 2;
K_N = M_.params( 14 );
B_K     = 1-1/K_N;
M_.params( 15 ) = 0.975;
gamma = M_.params( 15 );
[RHOSS,sigma_lomegaSS, muSS, Eomega_downSS, ALPHA_omegaSS, GAMMA_omegaSS, CE_KSS, WE_KSS, nuSS, a1SS, b1SS, a3SS, b3SS, a4SS, b4SS, a12SS, b12SS, a14SS, b14SS] = BGG_ss(beta_C,RK,delta, alpha, B_K, gamma, DEF_RATE); 
RHO = RHOSS;
M_.params( 16 ) = sigma_lomegaSS;
sigma_lomega = M_.params( 16 );
M_.params( 17 ) = muSS;
mu = M_.params( 17 );
Eomega_down = Eomega_downSS;
ALPHA_omega = ALPHA_omegaSS;
GAMMA_omega = GAMMA_omegaSS;
CE_K = CE_KSS;
M_.params( 18 ) = M_.params(42)*CE_K/M_.params(11);
CE_Y = M_.params( 18 );
M_.params( 19 ) = M_.params(48)-M_.params(18);
C_Y = M_.params( 19 );
M_.params( 20 ) = nuSS;
nu = M_.params( 20 );
M_.params( 24 ) = 0.75;
theta_h = M_.params( 24 );
M_.params( 25 ) = 0.5;
chi_h = M_.params( 25 );
M_.params( 21 ) = 0.8125;
theta_w = M_.params( 21 );
M_.params( 22 ) = 1.0;
chi_w = M_.params( 22 );
M_.params( 23 ) = 6.0;
eps_L = M_.params( 23 );
M_.params( 26 ) = 0.875;
theta_f = M_.params( 26 );
M_.params( 27 ) = 1.0;
chi_f = M_.params( 27 );
M_.params( 28 ) = 0;
rho_i = M_.params( 28 );
M_.params( 29 ) = 1.5;
phi_pic = M_.params( 29 );
M_.params( 30 ) = 0.125;
phi_y = M_.params( 30 );
M_.params( 31 ) = 0.0;
phi_dep = M_.params( 31 );
M_.params( 32 ) = 0.95;
rho_a = M_.params( 32 );
M_.params( 33 ) = 0.95;
rho_g = M_.params( 33 );
M_.params( 34 ) = 0.00;
rho_z = M_.params( 34 );
M_.params( 50 ) = 0.97;
rho_rnomstar = M_.params( 50 );
M_.params( 51 ) = 0.55;
rho_pistar = M_.params( 51 );
M_.params( 52 ) = 0.97;
rho_prcostar = M_.params( 52 );
M_.params( 53 ) = 0.95;
rho_yco = M_.params( 53 );
M_.params( 54 ) = 0.85;
rho_ystar = M_.params( 54 );
M_.params( 62 ) = 0.70;
sigma_a = M_.params( 62 );
M_.params( 61 ) = 1.50;
sigma_g = M_.params( 61 );
M_.params( 60 ) = 0.25;
sigma_z = M_.params( 60 );
M_.params( 55 ) = 0.25;
sigma_rnomstar = M_.params( 55 );
M_.params( 56 ) = 0.125;
sigma_pistar = M_.params( 56 );
M_.params( 57 ) = 13.0;
sigma_prcostar = M_.params( 57 );
M_.params( 58 ) = 4.0;
sigma_yco = M_.params( 58 );
M_.params( 59 ) = 1.0;
sigma_ystar = M_.params( 59 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = 0;
oo_.steady_state( 2 ) = 0;
oo_.steady_state( 3 ) = 0;
oo_.steady_state( 9 ) = 0;
oo_.steady_state( 5 ) = 0;
oo_.steady_state( 4 ) = 0;
oo_.steady_state( 6 ) = 0;
oo_.steady_state( 8 ) = 0;
oo_.steady_state( 7 ) = 0;
oo_.steady_state( 10 ) = 0;
oo_.steady_state( 11 ) = 0;
oo_.steady_state( 12 ) = 0;
oo_.steady_state( 13 ) = 0;
oo_.steady_state( 14 ) = 0;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 16 ) = 0;
oo_.steady_state( 17 ) = 0;
oo_.steady_state( 18 ) = 0;
oo_.steady_state( 19 ) = 0;
oo_.steady_state( 20 ) = 0;
oo_.steady_state( 21 ) = 0;
oo_.steady_state( 22 ) = 0;
oo_.steady_state( 23 ) = 0;
oo_.steady_state( 24 ) = 0;
oo_.steady_state( 25 ) = 0;
oo_.steady_state( 26 ) = 0;
oo_.steady_state( 27 ) = 0;
oo_.steady_state( 28 ) = 0;
oo_.steady_state( 29 ) = 0;
oo_.steady_state( 30 ) = 0;
oo_.steady_state( 31 ) = 0;
oo_.steady_state( 32 ) = 0;
oo_.steady_state( 33 ) = 0;
oo_.steady_state( 34 ) = 0;
oo_.steady_state( 35 ) = 0;
oo_.steady_state( 36 ) = 0;
oo_.steady_state( 37 ) = 0;
oo_.steady_state( 38 ) = 0;
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
resid;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(2, 2) = (1)^2;
M_.Sigma_e(3, 3) = (1)^2;
M_.Sigma_e(4, 4) = (1)^2;
M_.Sigma_e(5, 5) = (1)^2;
M_.Sigma_e(6, 6) = (1)^2;
M_.Sigma_e(7, 7) = (1)^2;
M_.Sigma_e(8, 8) = (1)^2;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 24;
options_.nograph = 1;
options_.order = 1;
var_list_ = char();
info = stoch_simul(var_list_);
save('bgg4_model0_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('bgg4_model0_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('bgg4_model0_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('bgg4_model0_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('bgg4_model0_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('bgg4_model0_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('bgg4_model0_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
