%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'GLS_compLabor';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('GLS_compLabor.log');
M_.exo_names = 'sh_G';
M_.exo_names_tex = 'sh\_G';
M_.exo_names_long = 'sh_G';
M_.exo_names = char(M_.exo_names, 'sh_zy');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_zy');
M_.exo_names_long = char(M_.exo_names_long, 'sh_zy');
M_.exo_names = char(M_.exo_names, 'sh_zM');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_zM');
M_.exo_names_long = char(M_.exo_names_long, 'sh_zM');
M_.endo_names = 'c_o';
M_.endo_names_tex = 'c\_o';
M_.endo_names_long = 'c_o';
M_.endo_names = char(M_.endo_names, 'omega_o');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_o');
M_.endo_names_long = char(M_.endo_names_long, 'omega_o');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'infT');
M_.endo_names_tex = char(M_.endo_names_tex, 'infT');
M_.endo_names_long = char(M_.endo_names_long, 'infT');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'ko');
M_.endo_names_tex = char(M_.endo_names_tex, 'ko');
M_.endo_names_long = char(M_.endo_names_long, 'ko');
M_.endo_names = char(M_.endo_names, 'xo');
M_.endo_names_tex = char(M_.endo_names_tex, 'xo');
M_.endo_names_long = char(M_.endo_names_long, 'xo');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'no');
M_.endo_names_tex = char(M_.endo_names_tex, 'no');
M_.endo_names_long = char(M_.endo_names_long, 'no');
M_.endo_names = char(M_.endo_names, 'nr');
M_.endo_names_tex = char(M_.endo_names_tex, 'nr');
M_.endo_names_long = char(M_.endo_names_long, 'nr');
M_.endo_names = char(M_.endo_names, 'c_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_r');
M_.endo_names_long = char(M_.endo_names_long, 'c_r');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'omega_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_r');
M_.endo_names_long = char(M_.endo_names_long, 'omega_r');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'tax');
M_.endo_names_tex = char(M_.endo_names_tex, 'tax');
M_.endo_names_long = char(M_.endo_names_long, 'tax');
M_.endo_names = char(M_.endo_names, 'taxr');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxr');
M_.endo_names_long = char(M_.endo_names_long, 'taxr');
M_.endo_names = char(M_.endo_names, 'taxo');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxo');
M_.endo_names_long = char(M_.endo_names_long, 'taxo');
M_.endo_names = char(M_.endo_names, 'zM');
M_.endo_names_tex = char(M_.endo_names_tex, 'zM');
M_.endo_names_long = char(M_.endo_names_long, 'zM');
M_.endo_names = char(M_.endo_names, 'zY');
M_.endo_names_tex = char(M_.endo_names_tex, 'zY');
M_.endo_names_long = char(M_.endo_names_long, 'zY');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'bg');
M_.endo_names_tex = char(M_.endo_names_tex, 'bg');
M_.endo_names_long = char(M_.endo_names_long, 'bg');
M_.endo_partitions = struct();
M_.param_names = 'betta';
M_.param_names_tex = 'betta';
M_.param_names_long = 'betta';
M_.param_names = char(M_.param_names, 'a');
M_.param_names_tex = char(M_.param_names_tex, 'a');
M_.param_names_long = char(M_.param_names_long, 'a');
M_.param_names = char(M_.param_names, 'del');
M_.param_names_tex = char(M_.param_names_tex, 'del');
M_.param_names_long = char(M_.param_names_long, 'del');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'thetaL');
M_.param_names_tex = char(M_.param_names_tex, 'thetaL');
M_.param_names_long = char(M_.param_names_long, 'thetaL');
M_.param_names = char(M_.param_names, 'alfa');
M_.param_names_tex = char(M_.param_names_tex, 'alfa');
M_.param_names_long = char(M_.param_names_long, 'alfa');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'infbar');
M_.param_names_tex = char(M_.param_names_tex, 'infbar');
M_.param_names_long = char(M_.param_names_long, 'infbar');
M_.param_names = char(M_.param_names, 'psiPi');
M_.param_names_tex = char(M_.param_names_tex, 'psiPi');
M_.param_names_long = char(M_.param_names_long, 'psiPi');
M_.param_names = char(M_.param_names, 'rhoI');
M_.param_names_tex = char(M_.param_names_tex, 'rhoI');
M_.param_names_long = char(M_.param_names_long, 'rhoI');
M_.param_names = char(M_.param_names, 'lamb');
M_.param_names_tex = char(M_.param_names_tex, 'lamb');
M_.param_names_long = char(M_.param_names_long, 'lamb');
M_.param_names = char(M_.param_names, 'rhoG');
M_.param_names_tex = char(M_.param_names_tex, 'rhoG');
M_.param_names_long = char(M_.param_names_long, 'rhoG');
M_.param_names = char(M_.param_names, 'rhozy');
M_.param_names_tex = char(M_.param_names_tex, 'rhozy');
M_.param_names_long = char(M_.param_names_long, 'rhozy');
M_.param_names = char(M_.param_names, 'gbar');
M_.param_names_tex = char(M_.param_names_tex, 'gbar');
M_.param_names_long = char(M_.param_names_long, 'gbar');
M_.param_names = char(M_.param_names, 'Rbar');
M_.param_names_tex = char(M_.param_names_tex, 'Rbar');
M_.param_names_long = char(M_.param_names_long, 'Rbar');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, 'eps');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'rhozM');
M_.param_names_tex = char(M_.param_names_tex, 'rhozM');
M_.param_names_long = char(M_.param_names_long, 'rhozM');
M_.param_names = char(M_.param_names, 'bbar');
M_.param_names_tex = char(M_.param_names_tex, 'bbar');
M_.param_names_long = char(M_.param_names_long, 'bbar');
M_.param_names = char(M_.param_names, 'phib');
M_.param_names_tex = char(M_.param_names_tex, 'phib');
M_.param_names_long = char(M_.param_names_long, 'phib');
M_.param_names = char(M_.param_names, 'phig');
M_.param_names_tex = char(M_.param_names_tex, 'phig');
M_.param_names_long = char(M_.param_names_long, 'phig');
M_.param_names = char(M_.param_names, 'noSS');
M_.param_names_tex = char(M_.param_names_tex, 'noSS');
M_.param_names_long = char(M_.param_names_long, 'noSS');
M_.param_names = char(M_.param_names, 'nrSS');
M_.param_names_tex = char(M_.param_names_tex, 'nrSS');
M_.param_names_long = char(M_.param_names_long, 'nrSS');
M_.param_names = char(M_.param_names, 'nSS');
M_.param_names_tex = char(M_.param_names_tex, 'nSS');
M_.param_names_long = char(M_.param_names_long, 'nSS');
M_.param_names = char(M_.param_names, 'qSS');
M_.param_names_tex = char(M_.param_names_tex, 'qSS');
M_.param_names_long = char(M_.param_names_long, 'qSS');
M_.param_names = char(M_.param_names, 'mcSS');
M_.param_names_tex = char(M_.param_names_tex, 'mcSS');
M_.param_names_long = char(M_.param_names_long, 'mcSS');
M_.param_names = char(M_.param_names, 'rkSS');
M_.param_names_tex = char(M_.param_names_tex, 'rkSS');
M_.param_names_long = char(M_.param_names_long, 'rkSS');
M_.param_names = char(M_.param_names, 'k_y');
M_.param_names_tex = char(M_.param_names_tex, 'k\_y');
M_.param_names_long = char(M_.param_names_long, 'k_y');
M_.param_names = char(M_.param_names, 'ySS');
M_.param_names_tex = char(M_.param_names_tex, 'ySS');
M_.param_names_long = char(M_.param_names_long, 'ySS');
M_.param_names = char(M_.param_names, 'kSS');
M_.param_names_tex = char(M_.param_names_tex, 'kSS');
M_.param_names_long = char(M_.param_names_long, 'kSS');
M_.param_names = char(M_.param_names, 'xSS');
M_.param_names_tex = char(M_.param_names_tex, 'xSS');
M_.param_names_long = char(M_.param_names_long, 'xSS');
M_.param_names = char(M_.param_names, 'xoSS');
M_.param_names_tex = char(M_.param_names_tex, 'xoSS');
M_.param_names_long = char(M_.param_names_long, 'xoSS');
M_.param_names = char(M_.param_names, 'koSS');
M_.param_names_tex = char(M_.param_names_tex, 'koSS');
M_.param_names_long = char(M_.param_names_long, 'koSS');
M_.param_names = char(M_.param_names, 'cSS');
M_.param_names_tex = char(M_.param_names_tex, 'cSS');
M_.param_names_long = char(M_.param_names_long, 'cSS');
M_.param_names = char(M_.param_names, 'wSS');
M_.param_names_tex = char(M_.param_names_tex, 'wSS');
M_.param_names_long = char(M_.param_names_long, 'wSS');
M_.param_names = char(M_.param_names, 'zYSS');
M_.param_names_tex = char(M_.param_names_tex, 'zYSS');
M_.param_names_long = char(M_.param_names_long, 'zYSS');
M_.param_names = char(M_.param_names, 'taxoSS');
M_.param_names_tex = char(M_.param_names_tex, 'taxoSS');
M_.param_names_long = char(M_.param_names_long, 'taxoSS');
M_.param_names = char(M_.param_names, 'taxrSS');
M_.param_names_tex = char(M_.param_names_tex, 'taxrSS');
M_.param_names_long = char(M_.param_names_long, 'taxrSS');
M_.param_names = char(M_.param_names, 'taxSS');
M_.param_names_tex = char(M_.param_names_tex, 'taxSS');
M_.param_names_long = char(M_.param_names_long, 'taxSS');
M_.param_names = char(M_.param_names, 'omega_oSS');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_oSS');
M_.param_names_long = char(M_.param_names_long, 'omega_oSS');
M_.param_names = char(M_.param_names, 'omega_rSS');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_rSS');
M_.param_names_long = char(M_.param_names_long, 'omega_rSS');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 26;
M_.param_nbr = 40;
M_.orig_endo_nbr = 26;
M_.aux_vars = [];
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('GLS_compLabor_static');
erase_compiled_function('GLS_compLabor_dynamic');
M_.orig_eq_nbr = 26;
M_.eq_nbr = 26;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 9 0;
 0 10 35;
 1 11 0;
 0 12 36;
 0 13 37;
 0 14 38;
 2 15 0;
 3 16 39;
 0 17 0;
 0 18 0;
 0 19 0;
 0 20 0;
 0 21 0;
 0 22 40;
 0 23 0;
 4 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 5 31 0;
 6 32 0;
 7 33 0;
 8 34 0;]';
M_.nstatic = 13;
M_.nfwrd   = 5;
M_.npred   = 7;
M_.nboth   = 1;
M_.nsfwrd   = 6;
M_.nspred   = 8;
M_.ndynamic   = 13;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(26, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(40, 1);
M_.NNZDerivatives = [94; -1; -1];
M_.params( 18 ) = 0;
bbar = M_.params( 18 );
hpar= 0.3;
M_.params( 8 ) = 1.007417071777733;
infbar = M_.params( 8 );
x_y  = 0.16;
M_.params( 14 ) = 0.2;
gbar = M_.params( 14 );
M_.params( 3 ) = 0.02411368908444489;
del = M_.params( 3 );
M_.params( 11 ) = 0.5;
lamb = M_.params( 11 );
M_.params( 1 ) = 0.99;
betta = M_.params( 1 );
real = 1/betta;
M_.params( 15 ) = real*M_.params(8);
Rbar = M_.params( 15 );
M_.params( 2 ) = 0.6;
a = M_.params( 2 );
M_.params( 4 ) = 0.2;
chi = M_.params( 4 );
M_.params( 7 ) = 77;
kappa = M_.params( 7 );
M_.params( 9 ) = 1.5;
psiPi = M_.params( 9 );
M_.params( 10 ) = 0.0;
rhoI = M_.params( 10 );
M_.params( 12 ) = 0.9;
rhoG = M_.params( 12 );
M_.params( 13 ) = 0.9;
rhozy = M_.params( 13 );
M_.params( 14 ) = 0.18;
gbar = M_.params( 14 );
M_.params( 16 ) = 6;
eps = M_.params( 16 );
M_.params( 17 ) = 0.0;
rhozM = M_.params( 17 );
M_.params( 19 ) = 0.33;
phib = M_.params( 19 );
M_.params( 20 ) = 0.01;
phig = M_.params( 20 );
M_.params( 21 ) = 0.3;
noSS = M_.params( 21 );
M_.params( 22 ) = 0.3;
nrSS = M_.params( 22 );
M_.params( 23 ) = 0.3;
nSS = M_.params( 23 );
M_.params( 24 ) = 1;
qSS = M_.params( 24 );
M_.params( 28 ) = 1;
ySS = M_.params( 28 );
M_.params( 25 ) = (M_.params(16)-1)/M_.params(16);
mcSS = M_.params( 25 );
M_.params( 26 ) = 1/M_.params(1)-(1-M_.params(3));
rkSS = M_.params( 26 );
M_.params( 27 ) = x_y/M_.params(3);
k_y = M_.params( 27 );
M_.params( 6 ) = M_.params(26)*M_.params(27)*1/M_.params(25);
alfa = M_.params( 6 );
M_.params( 29 ) = M_.params(27)*M_.params(28);
kSS = M_.params( 29 );
M_.params( 35 ) = M_.params(29)^(-M_.params(6))*M_.params(23)^(-(1-M_.params(6)));
zYSS = M_.params( 35 );
M_.params( 30 ) = M_.params(3)*M_.params(29);
xSS = M_.params( 30 );
M_.params( 31 ) = M_.params(30)/(1-M_.params(11));
xoSS = M_.params( 31 );
M_.params( 32 ) = M_.params(29)/(1-M_.params(11));
koSS = M_.params( 32 );
M_.params( 33 ) = M_.params(28)*(1-x_y-M_.params(14)/M_.params(28));
cSS = M_.params( 33 );
M_.params( 34 ) = M_.params(28)*M_.params(25)*(1-M_.params(6))/M_.params(23);
wSS = M_.params( 34 );
M_.params( 5 ) = M_.params(34)/(M_.params(33)*M_.params(23)^M_.params(4));
thetaL = M_.params( 5 );
M_.params( 36 ) = (M_.params(23)*(1-M_.params(11))*M_.params(34)+M_.params(26)*M_.params(29)+M_.params(28)-M_.params(25)*M_.params(28)-(1-M_.params(11))*M_.params(33)-M_.params(30))/(1-M_.params(11));
taxoSS = M_.params( 36 );
M_.params( 37 ) = (M_.params(23)*M_.params(11)*M_.params(34)-M_.params(11)*M_.params(33))/M_.params(11);
taxrSS = M_.params( 37 );
M_.params( 38 ) = M_.params(14);
taxSS = M_.params( 38 );
M_.params( 39 ) = 1/M_.params(33);
omega_oSS = M_.params( 39 );
M_.params( 40 ) = 1/M_.params(33);
omega_rSS = M_.params( 40 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = log(M_.params(33));
oo_.steady_state( 2 ) = log(M_.params(39));
oo_.steady_state( 3 ) = log(M_.params(15));
oo_.steady_state( 4 ) = log(M_.params(8));
oo_.steady_state( 5 ) = log(M_.params(26));
oo_.steady_state( 6 ) = 0;
oo_.steady_state( 7 ) = log(M_.params(32));
oo_.steady_state( 8 ) = log(M_.params(31));
oo_.steady_state( 9 ) = log(M_.params(34));
oo_.steady_state( 10 ) = log(M_.params(23));
oo_.steady_state( 11 ) = log(M_.params(22));
oo_.steady_state( 12 ) = log(M_.params(33));
oo_.steady_state( 13 ) = log(M_.params(25));
oo_.steady_state( 14 ) = log(M_.params(28));
oo_.steady_state( 15 ) = log(M_.params(40));
oo_.steady_state( 16 ) = log(M_.params(29));
oo_.steady_state( 17 ) = log(M_.params(23));
oo_.steady_state( 18 ) = log(M_.params(30));
oo_.steady_state( 19 ) = log(M_.params(33));
oo_.steady_state( 20 ) = M_.params(14);
oo_.steady_state( 22 ) = M_.params(36);
oo_.steady_state( 21 ) = M_.params(37);
oo_.steady_state( 23 ) = 0;
oo_.steady_state( 24 ) = log(M_.params(35));
oo_.steady_state( 25 ) = M_.params(14);
oo_.steady_state( 26 ) = M_.params(18);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
resid;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.1)^2;
options_.irf = 20;
options_.nograph = 1;
options_.order = 1;
var_list_ = char('c','c_r','c_o','y','x','rk','w','infT','tax','n','nr','no','g','R','bg');
info = stoch_simul(var_list_);
Rgov_real=Rbar/infbar; 
disc=1/Rgov_real;
disc_vec=disc.^[0:1:length(g_sh_G)-1];
mult_cum = cumsum(y_sh_G)./cumsum(g_sh_G); 
mult_pv=cumsum(disc_vec'.*y_sh_G)./cumsum(disc_vec'.*(g_sh_G));
disp(' ');
disp('Government expenditure Fiscal Multipliers:');
disp('-------------------------------------------------------------------------------------------------------------');
fprintf('                                            1Q     4Q     8Q     16Q     20Q     Inf     Max     Min\n' );
fprintf(['PV Fiscal Multipliers                    : %3.2f\t %3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\n'],...
        mult_pv(1),mult_pv(4),mult_pv(8),mult_pv(16),mult_pv(20),mult_pv(end),max(mult_pv),min(mult_pv));
fprintf('Cumulative Fiscal Multipliers            : %3.2f\t %3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\n',...
        mult_cum(1),mult_cum(4),mult_cum(8),mult_cum(16),mult_cum(20),mult_cum(end),max(mult_cum),min(mult_cum));
disp('-------------------------------------------------------------------------------------------------------------');
disp(' ');
w_sh_G(abs(w_sh_G)<1e-14)=0;
y_sh_G(abs(y_sh_G)<1e-14)=0;
c_sh_G(abs(c_sh_G)<1e-14)=0;
c_r_sh_G(abs(c_r_sh_G)<1e-14)=0;
c_o_sh_G(abs(c_o_sh_G)<1e-14)=0;
n_sh_sh_G(abs(n_sh_G)<1e-14)=0;
g_sh_G(abs(g_sh_G)<1e-14)=0;
bg_sh_G(abs(bg_sh_G)<1e-14)=0;
x_sh_G(abs(x_sh_G)<1e-14)=0;
no_sh_G(abs(no_sh_G)<1e-14)=0;
nr_sh_G(abs(nr_sh_G)<1e-14)=0;
tax_sh_G(abs(tax_sh_G)<1e-14)=0;
figure()
T = size(c_sh_G ,1);
t = 1:1:T;
subplot(3,2,1);
plot(t',(cSS/ySS)*c_sh_G,'b-', t', g_sh_G, 'r-', t', (xSS/ySS)*x_sh_G, 'g', t', y_sh_G, 'k-',  'LineWidth',2)
title(['Consumption, Gov. Expen, output, Investment'],'FontSize',8,'FontWeight','bold');
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
legend ('Consumption', 'Gov. Expen', 'Investment', 'Output');
xlim([1 T]);
grid on;
subplot(3,2,3);
pl=plot(t',w_sh_G, t',infT_sh_G', t',R_sh_G');
title(['Real Wage, Inflation, Interest Rates'],'FontSize',8,'FontWeight','bold');
pl(1).LineWidth = 2;
pl(1).Color='black';
pl(2).LineWidth = 2;
pl(2).Color='blue';
pl(3).LineWidth = 2;
pl(3).Color='green';
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
legend ('Real Wages', 'Inflation', 'Interest rates');
xlim([1 T]);
grid on;
subplot(3,2,2);
pl= plot(t',n_sh_G,t', no_sh_G, t', nr_sh_G);
title(['Labour'],'FontSize',8,'FontWeight','bold');
pl(1).Color='red';
pl(1).LineWidth = 2;
pl(2).Color='blue';
pl(3).Color='black';
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
legend ('Total Labour', 'Optimizers', 'Rule of Thumb');
xlim([1 T]);
grid on;
subplot(3,2,6);
pl=plot(t',y_sh_G./(g_sh_G(1)));
pl(1).LineWidth = 2;
pl(1).Color='black';
title(['Multiplier'],'FontSize',8,'FontWeight','bold');
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
xlim([1 T]);
grid on;
subplot(3,2,4);
pl=plot(t',tax_sh_G, t', g_sh_G', t',bg_sh_G);
pl(1).LineWidth = 2;
pl(1).Color='black';
pl(1).LineWidth = 2;
pl(1).Color='blue';
title(['Lump-sum Taxes and Expenditures'],'FontSize',8,'FontWeight','bold');
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
legend ('Taxes', 'Government Expenditure', 'debt');
xlim([1 T]);
grid on;
subplot(3,2,5);
plot(t',(cSS/ySS)*c_sh_G,'b-', t', (cSS/ySS)*c_r_sh_G, 'r-', t', (cSS/ySS)*c_o_sh_G, 'g-')
title(['Consumption'],'FontSize',8,'FontWeight','bold');
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
legend ('Consumption', 'RoT', 'Ricardian');
xlim([1 T]);
grid on;
print -dpdf GLS_Competitive.pdf
save('GLS_compLabor_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('GLS_compLabor_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('GLS_compLabor_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('GLS_compLabor_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('GLS_compLabor_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('GLS_compLabor_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('GLS_compLabor_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
