
params=[BETA,EPSILON,GAMMA_M,GAMMA,A_STEADY,RHO,KAPPA,PSI,VARPHI,SIGMA,ETA,G_STEADY];

OMEGA_STEADY = fsolve(@(x) omega_steady_func(x,params),0.5);


INT_STEADY = 1/BETA-1;
R_STEADY = 1/BETA-1;
PI_STEADY = 0;
MC_STEADY = (EPSILON-1)/EPSILON;
A_STEADY = 1;

Q_STEADY = GAMMA_M*OMEGA_STEADY^(-GAMMA);
P_STEADY = GAMMA_M*OMEGA_STEADY^(1-GAMMA);

W_STEADY = MC_STEADY*A_STEADY+(1/(1+R_STEADY))*RHO*(KAPPA/Q_STEADY)-KAPPA/Q_STEADY;
U_STEADY = 1 / (1+Q_STEADY*OMEGA_STEADY/(1-RHO));
V_STEADY = OMEGA_STEADY*U_STEADY;
L_STEADY = Q_STEADY*V_STEADY/(1-RHO);
Y_STEADY = A_STEADY*L_STEADY;
C_STEADY = Y_STEADY-G_STEADY;
MRS_STEADY = PSI*(L_STEADY^VARPHI)/(C_STEADY^(-SIGMA));

ss_vec = OMEGA_STEADY;

save('ss_vec','ss_vec');