%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NKMGasto_GHH_Dist_Tax';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NKMGasto_GHH_Dist_Tax.log');
M_.exo_names = 'sh_G';
M_.exo_names_tex = 'sh\_G';
M_.exo_names_long = 'sh_G';
M_.exo_names = char(M_.exo_names, 'sh_R');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_R');
M_.exo_names_long = char(M_.exo_names_long, 'sh_R');
M_.exo_names = char(M_.exo_names, 'sh_zY');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_zY');
M_.exo_names_long = char(M_.exo_names_long, 'sh_zY');
M_.exo_names = char(M_.exo_names, 'sh_tauL');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_tauL');
M_.exo_names_long = char(M_.exo_names_long, 'sh_tauL');
M_.exo_names = char(M_.exo_names, 'sh_tauK');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_tauK');
M_.exo_names_long = char(M_.exo_names_long, 'sh_tauK');
M_.exo_names = char(M_.exo_names, 'sh_tauC');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_tauC');
M_.exo_names_long = char(M_.exo_names_long, 'sh_tauC');
M_.endo_names = 'lambda';
M_.endo_names_tex = 'lambda';
M_.endo_names_long = 'lambda';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'infT');
M_.endo_names_tex = char(M_.endo_names_tex, 'infT');
M_.endo_names_long = char(M_.endo_names_long, 'infT');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'prof');
M_.endo_names_tex = char(M_.endo_names_tex, 'prof');
M_.endo_names_long = char(M_.endo_names_long, 'prof');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'Qx');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qx');
M_.endo_names_long = char(M_.endo_names_long, 'Qx');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'zY');
M_.endo_names_tex = char(M_.endo_names_tex, 'zY');
M_.endo_names_long = char(M_.endo_names_long, 'zY');
M_.endo_names = char(M_.endo_names, 'taxK');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxK');
M_.endo_names_long = char(M_.endo_names_long, 'taxK');
M_.endo_names = char(M_.endo_names, 'taxL');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxL');
M_.endo_names_long = char(M_.endo_names_long, 'taxL');
M_.endo_names = char(M_.endo_names, 'taxC');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxC');
M_.endo_names_long = char(M_.endo_names_long, 'taxC');
M_.endo_names = char(M_.endo_names, 'tauK');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauK');
M_.endo_names_long = char(M_.endo_names_long, 'tauK');
M_.endo_names = char(M_.endo_names, 'tauL');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauL');
M_.endo_names_long = char(M_.endo_names_long, 'tauL');
M_.endo_names = char(M_.endo_names, 'tauC');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauC');
M_.endo_names_long = char(M_.endo_names_long, 'tauC');
M_.endo_names = char(M_.endo_names, 'tr');
M_.endo_names_tex = char(M_.endo_names_tex, 'tr');
M_.endo_names_long = char(M_.endo_names_long, 'tr');
M_.endo_names = char(M_.endo_names, 'bg');
M_.endo_names_tex = char(M_.endo_names_tex, 'bg');
M_.endo_names_long = char(M_.endo_names_long, 'bg');
M_.endo_partitions = struct();
M_.param_names = 'sigma_c';
M_.param_names_tex = 'sigma\_c';
M_.param_names_long = 'sigma_c';
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'thetaL');
M_.param_names_tex = char(M_.param_names_tex, 'thetaL');
M_.param_names_long = char(M_.param_names_long, 'thetaL');
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'gbar');
M_.param_names_tex = char(M_.param_names_tex, 'gbar');
M_.param_names_long = char(M_.param_names_long, 'gbar');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names_long = char(M_.param_names_long, 'rhog');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'iota_n');
M_.param_names_tex = char(M_.param_names_tex, 'iota\_n');
M_.param_names_long = char(M_.param_names_long, 'iota_n');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, 'eps');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'inf_bar');
M_.param_names_tex = char(M_.param_names_tex, 'inf\_bar');
M_.param_names_long = char(M_.param_names_long, 'inf_bar');
M_.param_names = char(M_.param_names, 'Rbar');
M_.param_names_tex = char(M_.param_names_tex, 'Rbar');
M_.param_names_long = char(M_.param_names_long, 'Rbar');
M_.param_names = char(M_.param_names, 'rho_pi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_pi');
M_.param_names_long = char(M_.param_names_long, 'rho_pi');
M_.param_names = char(M_.param_names, 'rhozY');
M_.param_names_tex = char(M_.param_names_tex, 'rhozY');
M_.param_names_long = char(M_.param_names_long, 'rhozY');
M_.param_names = char(M_.param_names, 'a');
M_.param_names_tex = char(M_.param_names_tex, 'a');
M_.param_names_long = char(M_.param_names_long, 'a');
M_.param_names = char(M_.param_names, 'alfa');
M_.param_names_tex = char(M_.param_names_tex, 'alfa');
M_.param_names_long = char(M_.param_names_long, 'alfa');
M_.param_names = char(M_.param_names, 'del');
M_.param_names_tex = char(M_.param_names_tex, 'del');
M_.param_names_long = char(M_.param_names_long, 'del');
M_.param_names = char(M_.param_names, 'rhoTauL');
M_.param_names_tex = char(M_.param_names_tex, 'rhoTauL');
M_.param_names_long = char(M_.param_names_long, 'rhoTauL');
M_.param_names = char(M_.param_names, 'rhoTauK');
M_.param_names_tex = char(M_.param_names_tex, 'rhoTauK');
M_.param_names_long = char(M_.param_names_long, 'rhoTauK');
M_.param_names = char(M_.param_names, 'rhoTauC');
M_.param_names_tex = char(M_.param_names_tex, 'rhoTauC');
M_.param_names_long = char(M_.param_names_long, 'rhoTauC');
M_.param_names = char(M_.param_names, 'phib_tr');
M_.param_names_tex = char(M_.param_names_tex, 'phib\_tr');
M_.param_names_long = char(M_.param_names_long, 'phib_tr');
M_.param_names = char(M_.param_names, 'lambdaSS');
M_.param_names_tex = char(M_.param_names_tex, 'lambdaSS');
M_.param_names_long = char(M_.param_names_long, 'lambdaSS');
M_.param_names = char(M_.param_names, 'cSS');
M_.param_names_tex = char(M_.param_names_tex, 'cSS');
M_.param_names_long = char(M_.param_names_long, 'cSS');
M_.param_names = char(M_.param_names, 'nSS');
M_.param_names_tex = char(M_.param_names_tex, 'nSS');
M_.param_names_long = char(M_.param_names_long, 'nSS');
M_.param_names = char(M_.param_names, 'wSS');
M_.param_names_tex = char(M_.param_names_tex, 'wSS');
M_.param_names_long = char(M_.param_names_long, 'wSS');
M_.param_names = char(M_.param_names, 'ySS');
M_.param_names_tex = char(M_.param_names_tex, 'ySS');
M_.param_names_long = char(M_.param_names_long, 'ySS');
M_.param_names = char(M_.param_names, 'mcSS');
M_.param_names_tex = char(M_.param_names_tex, 'mcSS');
M_.param_names_long = char(M_.param_names_long, 'mcSS');
M_.param_names = char(M_.param_names, 'profSS');
M_.param_names_tex = char(M_.param_names_tex, 'profSS');
M_.param_names_long = char(M_.param_names_long, 'profSS');
M_.param_names = char(M_.param_names, 'xSS');
M_.param_names_tex = char(M_.param_names_tex, 'xSS');
M_.param_names_long = char(M_.param_names_long, 'xSS');
M_.param_names = char(M_.param_names, 'kSS');
M_.param_names_tex = char(M_.param_names_tex, 'kSS');
M_.param_names_long = char(M_.param_names_long, 'kSS');
M_.param_names = char(M_.param_names, 'rkSS');
M_.param_names_tex = char(M_.param_names_tex, 'rkSS');
M_.param_names_long = char(M_.param_names_long, 'rkSS');
M_.param_names = char(M_.param_names, 'zYSS');
M_.param_names_tex = char(M_.param_names_tex, 'zYSS');
M_.param_names_long = char(M_.param_names_long, 'zYSS');
M_.param_names = char(M_.param_names, 'tauKSS');
M_.param_names_tex = char(M_.param_names_tex, 'tauKSS');
M_.param_names_long = char(M_.param_names_long, 'tauKSS');
M_.param_names = char(M_.param_names, 'tauCSS');
M_.param_names_tex = char(M_.param_names_tex, 'tauCSS');
M_.param_names_long = char(M_.param_names_long, 'tauCSS');
M_.param_names = char(M_.param_names, 'tauLSS');
M_.param_names_tex = char(M_.param_names_tex, 'tauLSS');
M_.param_names_long = char(M_.param_names_long, 'tauLSS');
M_.param_names = char(M_.param_names, 'bgSS');
M_.param_names_tex = char(M_.param_names_tex, 'bgSS');
M_.param_names_long = char(M_.param_names_long, 'bgSS');
M_.param_names = char(M_.param_names, 'taxKSS');
M_.param_names_tex = char(M_.param_names_tex, 'taxKSS');
M_.param_names_long = char(M_.param_names_long, 'taxKSS');
M_.param_names = char(M_.param_names, 'taxLSS');
M_.param_names_tex = char(M_.param_names_tex, 'taxLSS');
M_.param_names_long = char(M_.param_names_long, 'taxLSS');
M_.param_names = char(M_.param_names, 'taxCSS');
M_.param_names_tex = char(M_.param_names_tex, 'taxCSS');
M_.param_names_long = char(M_.param_names_long, 'taxCSS');
M_.param_names = char(M_.param_names, 'trSS');
M_.param_names_tex = char(M_.param_names_tex, 'trSS');
M_.param_names_long = char(M_.param_names_long, 'trSS');
M_.param_names = char(M_.param_names, 'x_y');
M_.param_names_tex = char(M_.param_names_tex, 'x\_y');
M_.param_names_long = char(M_.param_names_long, 'x_y');
M_.param_names = char(M_.param_names, 'k_y');
M_.param_names_tex = char(M_.param_names_tex, 'k\_y');
M_.param_names_long = char(M_.param_names_long, 'k_y');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 6;
M_.endo_nbr = 23;
M_.param_nbr = 41;
M_.orig_endo_nbr = 23;
M_.aux_vars = [];
M_.Sigma_e = zeros(6, 6);
M_.Correlation_matrix = eye(6, 6);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NKMGasto_GHH_Dist_Tax_static');
erase_compiled_function('NKMGasto_GHH_Dist_Tax_dynamic');
M_.orig_eq_nbr = 23;
M_.eq_nbr = 23;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 12 35;
 0 13 0;
 0 14 0;
 0 15 0;
 0 16 36;
 1 17 0;
 2 18 37;
 0 19 0;
 0 20 0;
 3 21 38;
 4 22 0;
 5 23 39;
 0 24 40;
 6 25 0;
 7 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 8 30 41;
 9 31 0;
 10 32 0;
 0 33 0;
 11 34 0;]';
M_.nstatic = 9;
M_.nfwrd   = 3;
M_.npred   = 7;
M_.nboth   = 4;
M_.nsfwrd   = 7;
M_.nspred   = 11;
M_.ndynamic   = 14;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:6];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(23, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(6, 1);
M_.params = NaN(41, 1);
M_.NNZDerivatives = [104; -1; -1];
M_.params( 4 ) = 0.9902427357425652;
betta = M_.params( 4 );
M_.params( 10 ) = 1.007417071777733;
inf_bar = M_.params( 10 );
M_.params( 1 ) = 1;
sigma_c = M_.params( 1 );
M_.params( 2 ) = 1;
chi = M_.params( 2 );
M_.params( 5 ) = 0.14;
gbar = M_.params( 5 );
M_.params( 6 ) = 0.8;
rhog = M_.params( 6 );
M_.params( 8 ) = 0.0;
iota_n = M_.params( 8 );
M_.params( 9 ) = 6;
eps = M_.params( 9 );
theta_c = 2/3;
M_.params( 7 ) = theta_c*(M_.params(9)-1)/((1-theta_c)*(1-theta_c*M_.params(4)));
kappa = M_.params( 7 );
calvoSlope = (eps-1)/kappa;
M_.params( 16 ) = 0.02411368908444489;
del = M_.params( 16 );
M_.params( 14 ) = 0.6;
a = M_.params( 14 );
M_.params( 12 ) = 1.5;
rho_pi = M_.params( 12 );
M_.params( 13 ) = 0.9;
rhozY = M_.params( 13 );
M_.params( 40 ) = 0.16;
x_y = M_.params( 40 );
M_.params( 17 ) = 0;
rhoTauL = M_.params( 17 );
M_.params( 18 ) = 0;
rhoTauK = M_.params( 18 );
M_.params( 19 ) = 0;
rhoTauC = M_.params( 19 );
M_.params( 32 ) = 0.10;
tauKSS = M_.params( 32 );
M_.params( 33 ) = 0.07;
tauCSS = M_.params( 33 );
M_.params( 34 ) = 0.02;
tauLSS = M_.params( 34 );
M_.params( 35 ) = 0;
bgSS = M_.params( 35 );
M_.params( 20 ) = 0.3;
phib_tr = M_.params( 20 );
M_.params( 11 ) = M_.params(10)/M_.params(4);
Rbar = M_.params( 11 );
M_.params( 25 ) = 1;
ySS = M_.params( 25 );
M_.params( 23 ) = 0.3;
nSS = M_.params( 23 );
QxSS = 1;
M_.params( 26 ) = (M_.params(9)-1)/M_.params(9);
mcSS = M_.params( 26 );
M_.params( 30 ) = (1/M_.params(4)-(1-M_.params(16))-M_.params(16)*M_.params(32)/M_.params(10))/(1-M_.params(32));
rkSS = M_.params( 30 );
M_.params( 41 ) = M_.params(40)/M_.params(16);
k_y = M_.params( 41 );
M_.params( 15 ) = M_.params(30)*M_.params(41)*1/M_.params(26);
alfa = M_.params( 15 );
M_.params( 29 ) = M_.params(41)*M_.params(25);
kSS = M_.params( 29 );
M_.params( 31 ) = M_.params(29)^(-M_.params(15))*M_.params(23)^(-(1-M_.params(15)));
zYSS = M_.params( 31 );
M_.params( 28 ) = M_.params(16)*M_.params(29);
xSS = M_.params( 28 );
M_.params( 22 ) = M_.params(25)*(1-M_.params(40)-M_.params(5)/M_.params(25));
cSS = M_.params( 22 );
M_.params( 24 ) = M_.params(25)*M_.params(26)*(1-M_.params(15))/M_.params(23);
wSS = M_.params( 24 );
M_.params( 3 ) = (1-M_.params(34))/(1+M_.params(33))*M_.params(24)/M_.params(23)^M_.params(2);
thetaL = M_.params( 3 );
M_.params( 21 ) = (M_.params(22)-M_.params(3)/(1+M_.params(2))*M_.params(23)^(1+M_.params(2)))^(-M_.params(1))/(1+M_.params(33));
lambdaSS = M_.params( 21 );
M_.params( 27 ) = M_.params(25)*(1-M_.params(26));
profSS = M_.params( 27 );
M_.params( 36 ) = M_.params(29)*M_.params(32)*(M_.params(30)-M_.params(16)/M_.params(10));
taxKSS = M_.params( 36 );
M_.params( 37 ) = M_.params(23)*M_.params(34)*M_.params(24);
taxLSS = M_.params( 37 );
M_.params( 38 ) = M_.params(33)*M_.params(22);
taxCSS = M_.params( 38 );
M_.params( 39 ) = M_.params(36)+M_.params(37)+M_.params(38)+M_.params(35)-M_.params(5)+M_.params(35)*M_.params(11)/M_.params(10);
trSS = M_.params( 39 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = log(M_.params(21));
oo_.steady_state( 2 ) = log(M_.params(22));
oo_.steady_state( 3 ) = log(M_.params(23));
oo_.steady_state( 4 ) = log(M_.params(24));
oo_.steady_state( 5 ) = log(M_.params(25));
oo_.steady_state( 6 ) = log(M_.params(11));
oo_.steady_state( 7 ) = log(M_.params(10));
oo_.steady_state( 8 ) = log(M_.params(26));
oo_.steady_state( 9 ) = log(M_.params(27));
oo_.steady_state( 10 ) = log(M_.params(28));
oo_.steady_state( 11 ) = log(M_.params(29));
oo_.steady_state( 12 ) = log(QxSS);
oo_.steady_state( 13 ) = log(M_.params(30));
oo_.steady_state( 14 ) = log(M_.params(5));
oo_.steady_state( 22 ) = M_.params(39);
oo_.steady_state( 20 ) = M_.params(34);
oo_.steady_state( 19 ) = M_.params(32);
oo_.steady_state( 21 ) = M_.params(33);
oo_.steady_state( 23 ) = M_.params(35);
oo_.steady_state( 16 ) = log(M_.params(36));
oo_.steady_state( 17 ) = log(M_.params(37));
oo_.steady_state( 18 ) = log(M_.params(38));
oo_.steady_state( 15 ) = log(M_.params(31));
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
options_.irf = 20;
options_.nograph = 1;
options_.noprint = 1;
options_.order = 1;
var_list_ = char();
info = stoch_simul(var_list_);
Rgov_real=Rbar/inf_bar; 
disc=1/Rgov_real;
disc_vec=disc.^[0:1:length(g_sh_G)-1];
mult_cum = cumsum(y_sh_G)./cumsum(g_sh_G*gbar); 
mult_pv=cumsum(disc_vec'.*y_sh_G)./cumsum(disc_vec'.*(g_sh_G*gbar));
disp(' ');
disp('Government expenditure Fiscal Multipliers:');
disp('-------------------------------------------------------------------------------------------------------------');
fprintf('                                            1Q     4Q     8Q     16Q     20Q     Inf     Max     Min\n' );
fprintf(['PV Fiscal Multipliers                    : %3.2f\t %3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\n'],...
        mult_pv(1),mult_pv(4),mult_pv(8),mult_pv(16),mult_pv(20),mult_pv(end),max(mult_pv),min(mult_pv));
fprintf('Cumulative Fiscal Multipliers            : %3.2f\t %3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\t%3.2f\n',...
        mult_cum(1),mult_cum(4),mult_cum(8),mult_cum(16),mult_cum(20),mult_cum(end),max(mult_cum),min(mult_cum));
disp('-------------------------------------------------------------------------------------------------------------');
disp(' ');
w_sh_G(abs(w_sh_G)<1e-8)=0;
y_sh_G(abs(y_sh_G)<1e-8)=0;
c_sh_G(abs(c_sh_G)<1e-8)=0;
n_sh_G(abs(n_sh_G)<1e-8)=0;
g_sh_G(abs(g_sh_G)<1e-8)=0;
x_sh_G(abs(x_sh_G)<1e-8)=0;
prof_sh_G(abs(prof_sh_G)<1e-8)=0;
wn_sh_G = wSS*w_sh_G+nSS*n_sh_G;
tax_sh_G = taxK_sh_G + taxL_sh_G + taxC_sh_G - tr_sh_G;
figure()
T = size(c_sh_G ,1);
t = 1:1:T;
subplot(3,2,1);
plot(t',(cSS/ySS)*c_sh_G,'b-', t', (gbar/ySS)*g_sh_G, 'r-', t', (xSS/ySS)*x_sh_G, 'g-', t', y_sh_G, 'k-',  'LineWidth',2)
title(['Consumption y Gov. Expen'],'FontSize',8,'FontWeight','bold');
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
legend ('Consumption', 'Gov. Expen', 'Investment', 'Output');
xlim([1 T]);
grid on;
subplot(3,2,2);
pl=plot(t',infT_sh_G', t',R_sh_G');
title(['Inflation, Interest Rates'],'FontSize',8,'FontWeight','bold');
pl(1).LineWidth = 2;
pl(1).Color='black';
pl(2).LineWidth = 2;
pl(2).Color='blue';
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
legend ('Inflation', 'Interest rates');
xlim([1 T]);
grid on;
subplot(3,2,3);
pl=plot(t',rk_sh_G, t',w_sh_G');
pl(1).LineWidth = 2;
pl(1).Color='black';
pl(2).LineWidth = 2;
pl(2).Color='blue';
title(['Rental rate of capital and real wage'],'FontSize',8,'FontWeight','bold');
ylabel('Basis pts. dev.','FontSize',8);
legend ('Rent of Capital', 'Real Wages');
set(gca,'Fontsize',8);
xlim([1 T]);
grid on;
subplot(3,2,4);
plot(t',n_sh_G,'b-','LineWidth',2)
title(['Labor'],'FontSize',8,'FontWeight','bold');
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
xlim([1 T]);
grid on;
subplot(3,2,5);
pl=plot(t',wn_sh_G', t',prof_sh_G');
title(['Wage bill and Profits'],'FontSize',8,'FontWeight','bold');
pl(1).LineWidth = 2;
pl(1).Color='black';
pl(2).LineWidth = 2;
pl(2).Color='blue';
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
legend ('Wage bill','Profits');
xlim([1 T]);
grid on;
subplot(3,2,5);
pl=plot(t',g_sh_G', t',tax_sh_G',t',bg_sh_G');
title(['Government'],'FontSize',8,'FontWeight','bold');
pl(1).LineWidth = 2;
pl(1).Color='black';
pl(2).LineWidth = 2;
pl(2).Color='blue';
pl(3).LineWidth = 2;
pl(3).Color='red';
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
legend ('Gov. Exp','Tax Rev', 'Public Debt');
xlim([1 T]);
grid on;
subplot(3,2,6);
pl=plot(t',taxK_sh_G', t',taxL_sh_G',t',taxC_sh_G', t',tr_sh_G');
title(['Taxes'],'FontSize',8,'FontWeight','bold');
pl(1).LineWidth = 2;
pl(1).Color='black';
pl(2).LineWidth = 2;
pl(2).Color='blue';
pl(3).LineWidth = 2;
pl(3).Color='green';
pl(4).LineWidth = 2;
pl(4).Color='red';
ylabel('Basis pts. dev.','FontSize',8);
set(gca,'Fontsize',8);
legend ('Capital','Labor','Consumption', 'Transfers');
xlim([1 T]);
grid on;
save('NKMGasto_GHH_Dist_Tax_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NKMGasto_GHH_Dist_Tax_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NKMGasto_GHH_Dist_Tax_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NKMGasto_GHH_Dist_Tax_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NKMGasto_GHH_Dist_Tax_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NKMGasto_GHH_Dist_Tax_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NKMGasto_GHH_Dist_Tax_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
